TrainSys/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from login import login_views
from class_op import class_op_views
from person_info import person_info_views
from test_op import test_op_views
from grade import grade_views

urlpatterns = [
    path('', login_views.login),
    path('admin/', admin.site.urls),

    # urls of login app, need to be moved inside login app
    path('login/', login_views.login),
    path('logout/', login_views.logout),
    path('register/', login_views.register),
    path('register/teacher_verify/', login_views.teacher_verify),

    path('classes/', include('class_op.urls')),
    path('user/', person_info_views.index),
    path('tests/', include('test_op.urls')),
    path('grade/', include('grade.urls')),
    path('main_session/', include('main_session.urls')),
    path('api/', include('api.urls')),
]

api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from api import api_views

urlpatterns = [
    # path('test/'),
    # path('test/page/'),
    path('submit_test/', api_views.submit_test),
    path('find_do_test_info_by_name/', api_views.find_do_test_info_by_name),
    path('find_test_by_name/', api_views.find_test_data_by_name),
    path('find_test_id_by_name/', api_views.find_test_id_by_name),
    path('find_do_test_by_name/', api_views.find_do_test_by_name),
    path('exercise_page_finished/', api_views.add_exercise_record),
    path('find_my_classes/', api_views.find_my_classes),
    url(r'find_test_by_id/(\d+)/', api_views.find_test_by_id),
    url(r'student_grade_detail/(\d+)/(\d+)/(\d+)/', api_views.student_grade_detail),
    url(r'get_chart_data/(\d+)/', api_views.get_chart_data),
    path('send_do_test_result/', api_views.receive_do_test_result),
    path('find_current_class/', api_views.find_current_class),
    path('find_img_server/', api_views.find_img_server),
    path('find_user/', api_views.find_user),
    url(r'search/$', api_views.search),
    path('upload_file/', api_views.upload_file),
    url(r'delete_file/(\d+)/([^\/\\\:\*\"\<\>\|\?]+\.\w+|\w+)/', api_views.delete_file),
]

class_op/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from class_op import class_op_views

urlpatterns = [
    path('', class_op_views.index),
    path('join/', class_op_views.joined_classes),
    path('create_new_class/', class_op_views.create_new_class),
    path('index/', class_op_views.index),
    path('mine/', class_op_views.mine_classes),
    url(r'(join|mine|index)/search/$', class_op_views.search_classes),
    url(r'search/$', class_op_views.search_classes),
    url(r'(\d+)/content_(\w+)/', class_op_views.class_content),
    # url(r'(\d+)/tests_list/', class_op_views.tests_list),
    url(r'(\d+)/join/', class_op_views.join_class),
    url(r'(\d+)/quit/', class_op_views.quit_class),
    url(r'(\d+)/delete/', class_op_views.delete_class),
    url(r'(\d+)/edit/', class_op_views.edit_class),
    url(r'(\d+)/do_test/(\d+)', class_op_views.do_test),
    url(r'(\d+)/', class_op_views.class_info, name='class_info'),
]

grade/urls.py
from django.urls import path
from django.conf.urls import url
from test_op import test_op_views
from grade import grade_views

urlpatterns = [
    path('', grade_views.index),
    path('index/',grade_views.index),
    path('tea_class/',grade_views.tea_class),
    url(r'(\d+)/test', grade_views.one_test_grade, name='one_test_grade'),
    url(r'(\d+)/student/(\d+)',grade_views.stu_one_class_grade, name='stu_one_class_grade'),
    url(r'(\d+)/', grade_views.one_class_grade, name='one_class_grade'),
]

main_session/urls.py
from django.urls import path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="index.html")),
    path('create_test/', TemplateView.as_view(template_name="create_test.html")),
    path('do_test/', TemplateView.as_view(template_name="do_test.html")),
]

test_op/urls.py
from django.urls import path
from django.conf.urls import url
from test_op import test_op_views

urlpatterns = [
    path('', test_op_views.index),
    path('index/', test_op_views.index),
    path('mine/', test_op_views.mine),
    path('join/', test_op_views.joined),
    path('create_new_test/', test_op_views.create_new_test),
    path('create_new_test_edit/', test_op_views.create_new_test_edit),
    url(r'(index|mine|join)/search/$', test_op_views.search_tests),
    url(r'search/$', test_op_views.search_tests),
    url(r'^(\d+)/delete/', test_op_views.delete_test),
    url(r'^(\d+)/edit/', test_op_views.edit_test),
    url(r'^(\d+)/edit_info/', test_op_views.edit_test_info),
    url(r'^(\d+)/(\d+)/', test_op_views.test_info_from_class, name='test_info_from_class'),
    url(r'^(\d+)/', test_op_views.test_info, name='test_info'),
    url(r'^class/(\d+)/', test_op_views.do_test, name='do_test'),
]

class_op/models.py
from django.db import models
from login.models import User
# Create your models here.


class Class(models.Model):
    name = models.CharField(max_length=64, unique=True)
    create_time = models.DateField(auto_now_add=True)
    teachers = models.ManyToManyField(User, related_name='own_classes_set')
    students = models.ManyToManyField(User, related_name='join_classes_set')
    cover = models.CharField(max_length=128, blank=True)
    chapter = models.CharField(max_length=4096, blank=True)
    files = models.CharField(max_length=1280)
    describe = models.CharField(max_length=1280, blank=True)


class notice(models.Model):
    _class = models.ForeignKey(Class, on_delete=models.CASCADE)
    detail = models.CharField(max_length=128, blank=True)
    publisher = models.ForeignKey(User, on_delete=models.CASCADE, related_name="publish_notice_set")
    receiver = models.ManyToManyField(User, related_name="receive_notice_set", null=True)

grade/models.py
from django.db import models
from test_op.models import Test
from login.models import User
from class_op.models import Class

# 用户完成一个页面的任务后会写入一条数据库记录
class Exercise(models.Model):
    test = models.ForeignKey(Test, on_delete=models.CASCADE, related_name="own_exercise_set")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="own_exercise_set")
    time = models.DateTimeField(auto_now_add=True)
    page = models.IntegerField()


# 记录用户做某个练习时花费的时间和点击次数
class DetailRecord(models.Model):
    test = models.ForeignKey(Test, on_delete=models.CASCADE, related_name="own_detailRecord_set")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="own_detailRecord_set")
    _class = models.ForeignKey(Class, on_delete=models.DO_NOTHING, related_name="own_detailRecord_set")
    spend_time = models.CharField(max_length=512)
    spend_click = models.CharField(max_length=512)


#class Exam(models.Model):

login/models.py
from django.db import models

# Create your models here.


class User(models.Model):
    username = models.CharField(max_length=32, unique=True)
    display_name = models.CharField(max_length=6, unique=False)
    password = models.CharField(max_length=64)
    create_time = models.DateField(auto_now_add=True)
    identity = models.CharField(max_length=8, choices=(('teacher', '教师'), ('student', '学生')), default='student')

    class Mete:
        ordering = ['create_time']

main_session/models.py
from django.db import models

# Create your models here.

person_info/models.py
from django.db import models
# Create your models here.

test_op/models.py
from django.db import models
from login.models import User
from class_op.models import Class
# Create your models here.


class Test(models.Model):
    name = models.CharField(max_length=64, unique=True)
    create_time = models.DateField(auto_now_add=True)
    describe = models.CharField(max_length=512, blank=True)
    data = models.TextField(max_length=1000000, blank=True)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE, related_name='own_tests_set')
    students = models.ManyToManyField(User, related_name='join_tests_set')
    classes = models.ManyToManyField(Class, through='ClassCrossTest')
    cover = models.CharField(max_length=128, blank=True)


class ClassCrossTest(models.Model):
    _class = models.ForeignKey(Class, on_delete=models.CASCADE)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    chapter = models.CharField(max_length=128, blank=True)
    date = models.DateField(auto_now_add=True)


class TestPage(models.Model):
    test = models.ForeignKey('Test', on_delete=models.CASCADE, default='')
    page = models.IntegerField(default=0)
    title = models.CharField(max_length=64)


class TestPageElement(models.Model):
    test_page = models.ForeignKey('TestPage', on_delete=models.CASCADE, default='')
    id = models.IntegerField(unique=True, primary_key=True)
    attributes = models.CharField(max_length=1024)

class_op/templates/class_op/class_info.html
{% extends 'base.html' %}

{% load static %}
{% block title %}首页{% endblock %}
{% block static %}
    <script src="{% static 'js/class_op/main.js' %}"></script>
    <link href="{% static 'css/class_op/index.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}
    <div class="container.fluid">
        {% if messages %}
            <script>
                {%
                for msg in messages %}
                alert('{{ msg.message }}');
                {%
                endfor %
                }
            </script>
        {% endif %}
        <div class="row"
             style="background: url({{ TEST_INFO_HEADER_IMG }}); background-size: cover;
                     background-position: bottom; padding-top: 5px; color: #ffffff;
                     height: 120px;">
            <div class="col-md-12">
                <div class="col-md-6 col-md-offset-2">
                    <div class="row">
                        <a class="class-info-title" style="font-size: 60px;"
                           data-id="{{ class.id }}">{{ class.name }}</a>
                    </div>
                    <div class="row">
                        <span>&nbsp;<b>授课教师:</b> {% for teacher in class.teachers %}
                            {{ teacher.display_name }} {% endfor %}&nbsp;&nbsp;&nbsp;&nbsp;</span>
                        <span><b>开课时间:</b> {{ class.create_time }}&nbsp;&nbsp;&nbsp;&nbsp;</span>
                        <span><b>参课人数:</b> {{ class.students_number }}</span>
                    </div>
                </div>
                <div style="right: 15%; position: absolute; padding-top: 65px;">
                <span>
                    {% if is_creator %}
                        <a class="btn btn-danger" style="float: right; margin-left: 4px;" href="delete/">
                            删除课程
                        </a>
                        <a class="btn btn-warning" style="float: right; margin-left: 4px;" href="edit/">
                            编辑课程
                        </a>
                    {% else %}
                        {% if is_member %}
                            <a class="btn btn-success" style="float: right;" href="quit/">
                               已加入课程
                            </a>
                        {% else %}
                            <a class="btn btn-primary" style="float: right;" href="join/">
                                加入课程
                            </a>
                        {% endif %}
                    {% endif %}
                </span>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="row" style="background: #f8f8f8;">
                <div class="col-md-offset-2 col-md-6">
                    <ul class="nav nav-pills class-info-tab">
                        <li><a class="class-content-tab" id="class_content_info" data-target="info">课程首页</a></li>
                        <li><a class="class-content-tab" data-target="chapter">章节信息</a></li>
                        <li><a class="class-content-tab" data-target="source">课程资源</a></li>
                        <li><a class="class-content-tab" data-target="exam">考核测验</a></li>
                        <li><a class="class-content-tab" data-target="discuss">研讨交流</a></li>
                        {% if is_creator %}
                            <li><a class="class-content-tab" data-target="notice">发布通知</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
            <div class="row divider-line-shadow"></div>
            <div class="row" id="class_content_container">
                {% include './components/class_content_info.html' %}
            </div>
        </div>
    </div>

    <!--流媒体点播-->
    <!--记录-->
    <!--问卷调查功能-->

{% endblock %}

class_op/templates/class_op/classes.html
{% extends 'base.html' %}

{% load static %}
{% block title %}首页{% endblock %}
{% block static %}
<script src="{% static 'js/class_op/main.js' %}"></script>
<link href="{% static 'css/class_op/index.css' %}" rel="stylesheet"/>
{% endblock %}

{% block content %}
<div class="container.fluid">
    {% if messages %}
    <script>
        {% for msg in messages %}
            alert('{{ msg.message }}');
        {% endfor %}
    </script>
    {% endif %}
    {% include 'jumbotron.html' %}
    <div class="row">
        <div class="col-md-5 col-md-offset-2">
            {% include './components/search.html' %}
        </div>
        {% if request.session.identity == 'teacher' %}
        <div class="col-md-1 col-md-offset-2">
            {% include './components/create.html' %}
        </div>
        {% endif %}
    </div>
    <br>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <ul class="nav nav-tabs">
                <li role="presentation" class="active"><a href="/classes/index/">全部课程</a></li>
                {% if request.session.identity == 'teacher' %}
                    <li role="presentation"><a href="/classes/mine/">我创建的课程</a></li>
                {% endif %}
                <li role="presentation"><a href="/classes/join/">我参加的课程</a></li>
            </ul>
            <br><br>
        </div>
    </div>
    {% include './components/classes_list.html' %}
</div>

<!--流媒体点播-->
<!--记录-->
<!--问卷调查功能-->

{% endblock %}

class_op/templates/class_op/components/class_content_chapter.html
{% load static %}
<script src="{% static 'js/bootstrap-select.min.js' %}"></script>
<script src="{% static 'js/class_op/class_content_chapter.js' %}"></script>
<link href="{% static 'css/bootstrap-select.min.css' %}" rel="stylesheet"/>
{% include './test_detail.html' %}

<div class="adjust-list" style="margin-top: 20px;">
    <div class="class-content-container">
        <div class="class-content-box">
            <div style="padding-left: 40px;padding-right: 40px;">
                <div style="white-space: nowrap;">
                    <b style="font-size: 20px;">课程简介:</b>
                    {% csrf_token %}
                    <button class="btn btn-danger" id="edit_class_content_cancel"
                            style="display: none; float: right; padding: 2px 6px;">取消
                    </button>
                    <button class="btn btn-success" id="edit_class_content_confirm"
                            style="display: none; float: right; padding: 2px 6px; margin-right: 10px;">提交
                    </button>
                    <button class="btn btn-info" id="edit_class_content_chapter"
                            style="float: right; padding: 2px 6px;">编辑
                    </button>
                </div>
                <div class="row class-content-line"></div>
                <input type="hidden" id="class_content_chapter_data" value="{{ chapters }}">
                <input type="hidden" id="class_content_chapter_source_map" value="{{ chapters_source_map }}">
                <div id="class_content_chapter_tree"></div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="chapter_edit_modal" style="position: absolute; left: 0px; top: 0px;" tabindex="-1"
         role="dialog">
        <div class="modal-dialog" style="position: absolute; margin: 0px;">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="form-group new-class-form-group">
                        <label class="new-class-label">章节标题:</label>
                        <input class="form-control" id="chapter_edit_modal_input_title" style="width: 550px;"
                               placeholder="输入编辑内容">
                    </div>
                    <div class="form-group new-class-form-group">
                        <label class="new-class-label">章节描述:</label>
                        <input class="form-control" id="chapter_edit_modal_input_title" style="width: 550px;"
                               placeholder="输入编辑内容">
                    </div>
                    <div class="form-group new-class-form-group">
                        <label class="new-class-label">章节资源:</label>
                        <select class="form-control selectpicker" id="chapter_edit_modal_select_source"
                                data-selected-text-format="count > 5" multiple title="未选择资源">
                            {% for test in tests %}
                                <option class="test-select-option"
                                        value={{ test.id }}>{{ test.name }}</option>
                            {% endfor %}
                            {% for file in files %}
                                <option class="test-select-option"
                                        value={{ file }}>{{ file }}</option>
                            {% endfor %}
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-dismiss="modal" id="chapter_edit_modal_confirm">
                        确定
                    </button>
                    <button type="button" class="btn" data-dismiss="modal">关闭</button>
                </div>
            </div>

            <br>
        </div>
    </div>
</div>

class_op/templates/class_op/components/class_content_info.html
<div class="adjust-list" style="margin-top: 20px;">
    <div class="class-content-container">
        <div class="class-content-box" style="width: 66.6%;">
            <div style="padding-left: 40px;padding-right: 40px;">
                <b style="font-size: 20px;">课程简介:</b>
                <div class="row class-content-line"></div>
                <div style="font-size: 18px; word-break:break-all;">&nbsp;&nbsp;&nbsp;&nbsp;{{ class.describe }}
                </div>
            </div>
        </div>
        <div class="class-content-box" style="width: 33.3%; margin-left: 15px;">
            <div style="padding-left: 40px;padding-right: 40px;">
                <b style="font-size: 20px;">教师介绍:</b>
                <div class="row class-content-line"></div>
                <div style="font-size: 18px; word-break:break-all;">
                </div>
            </div>
        </div>
    </div>
</div>

class_op/templates/class_op/components/class_content_source.html
{% load static %}
<script src="{% static 'js/class_op/class_content_source.js' %}"></script>

<div class="adjust-list" style="margin-top: 20px;">
    <div class="class-content-container">
        <div class="class-content-box">
            <div style="padding-left: 40px;padding-right: 40px;">
                <b style="font-size: 20px;">课程练习:</b>
                <div class="row class-content-line"></div>
                <div style="white-space: nowrap; margin-top: 25px; max-height: 600px; overflow: auto;">
                    {% include './tests_list.html' %}
                </div>
            </div>
        </div>
    </div>
    <div class="class-content-container" style="margin-top: 25px;">
        <div class="class-content-box">
            <div style="padding-left: 40px;padding-right: 40px;">
                <b style="font-size: 20px;">课程资料:</b>
                <div class="row class-content-line"></div>
                <div style="white-space: nowrap; margin-top: 25px; max-height: 600px; overflow: auto;">
                    {% include './files_list.html' %}
                </div>
            </div>
        </div>
    </div>
</div>

class_op/templates/class_op/components/classes_list.html
{% load static %}

<div class="row class-list">
    <div class="adjust-list">
        {% for set4 in page_data %}
            <div class="row" style="display: flex; width: 1200px; margin-bottom: 30px;">
            {% for class in set4 %}
                <div class="class-info">
                    <a href="/classes/{{ class.id }}">
                        {% if class.cover == "?w=250&h=200" %}
                            <img class="class-cover" src={% static 'img/default_cover.jpg' %}>
                        {% else %}
                            <img class="class-cover" src="{{ class.cover }}">
                        {% endif %}
                    </a>
                    <div class="class-title-info">
                        <a class="class-title" href="/classes/{{ class.id }}" title="{{ class.name }}">
                            {{ class.name }}
                        </a>
                        <p class="class-detail-info">
                            <i class="glyphicon glyphicon-user"></i>
                            {{ class.students_number }}
                        </p>
                    </div>
                </div>
            {% endfor %}
            </div>
            <br><br>
        {% endfor %}
    </div>
</div>

class_op/templates/class_op/components/create.html
<button class="btn btn-primary" data-toggle="modal" data-target="#create_new_class_modal" id="create_new_class_btn">创建新课程</button>

<div class="modal fade" id="create_new_class_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel"><b>创建新课程</b></h4>
            </div>
            <div class="modal-body">
                <form id="new_class_form" class="new-class-form" method="post" target="hidden-post-frame">
                    {% csrf_token %}
                    <div class="form-group">
                        <div class="new-class-form-group">
                            <label for="new_class_name" class="new-class-label text-center">课程名称：</label>
                            <input type="text" name='new_class_name' class="form-control" id="new_class_name" placeholder="请输入课程名称" autofocus required>
                        </div>
                        <br>
                        <div class="new-class-form-group">
                            <label for="new_class_describe" class="new-class-label text-center">课程描述：</label>
                            <textarea name='new_class_describe' class="form-control new-class-describe" id="new_class_describe" placeholder="请输入课程描述" required maxlength="128"></textarea>
                        </div>
                        <br>
                        <input name="new_class_cover" id="new_class_cover" style="height: 0px; width: 0px; border: 0; padding: 0;">
                    </div>
                </form>
                <div class="new-class-form-group">
                    <label for="new_class_img_uploader" class="new-class-label text-center">上传封面：</label>
                    <button id="new_class_img_upload_btn" class="new-class-img-preview" url="{{ IMG_SERVER }}">
                        <span class="glyphicon glyphicon-plus"></span>
                    </button>
                    <input type="file" id="new_class_img_uploader" accept=".jpg, .jpeg, .png">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
                <button type="submit" class="btn btn-primary" id="new_class_submit">确定</button>
            </div>
        </div>
    </div>
</div>

class_op/templates/class_op/components/files_list.html
<div class="adjust-list">
    {% for file in files %}
        <div class="row" style="display: flex; width: 100%; margin-bottom: 30px;">
            <a href="/static/uploads/{{ class.id }}/{{ file }}">{{ file }}</a>
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <a href="/api/delete_file/{{ class.id }}/{{ file }}">删除</a>
        </div>
    {% endfor %}
</div>

class_op/templates/class_op/components/search.html
<div class="" role="search">
    <div class="input-group">
        <span class="input-group-addon" style="background-color: #2b669a; color: #ffffff;">搜索课程</span>
        <input type="text" class="form-control" id="search_input_class" style="width: 100%;"  placeholder="请输入课程名称">
        <span class="input-group-btn">
            <button class="btn btn-default" id="search_btn_class">搜索</button>
        </span>
    </div>
</div>

class_op/templates/class_op/components/test_detail.html
{% load static %}
<div class="modal fade" id="show_test_detail_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel"><b>练习详情</b></h4>
            </div>
            <div class="modal-body">
                <div id="new_class_form" class="new-class-form">
                    <div class="form-group">
                        <div style="display: flex; flex-direction: row;">
                            <div>
                                <img class="test-detail-cover" id="test_detail_cover">
                            </div>
                            <div style="display: flex; flex-direction: column; width: 100%;">
                                <div class="new-class-form-group" style="height: 30px; margin: 10px 0px 10px 20px;">
                                    <label class="new-class-label text-center"
                                           style="width: 100px!important;">练习名称：</label>
                                    <div id="test_detail_name" style="white-space: pre-line; font-size: 18px;"></div>
                                </div>
                                <div class="new-class-form-group" style="height: 30px; margin: 10px 0px 10px 20px;">
                                    <label class="new-class-label text-center"
                                           style="width: 100px!important;">创建教师：</label>
                                    <div id="test_detail_teacher" style="white-space: pre-line; font-size: 18px;"></div>
                                </div>
                            </div>
                            <button id="do_test_btn" class="btn btn-default">开始做练习</button>
                        </div>
                        <br>
                        <div class="new-class-form-group">
                            <label class="new-class-label text-center">练习描述：</label>
                            <div id="test_detail_describe" style="white-space: pre-line; font-size: 18px;"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" id="jump_to_test_btn">转到练习页面</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
            </div>
        </div>
    </div>
</div>

grade/templates/grade/components/search.html
<form class="" role="search">
    <div class="input-group">
        <span class="input-group-addon" style="background-color: #2b669a; color: #ffffff;">搜索课程</span>
        <input type="text" style="width: 100%;" class="form-control" placeholder="请输入课程名称">
        <span class="input-group-btn">
            <button type="submit" class="btn btn-default">搜索</button>
        </span>
    </div>
</form>

grade/templates/grade/components/student_modal.html
<div class="modal fade" id="student_test" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
					&times;
				</button>
				<div class="modal-title" id="username" style="font-weight: 700; font-size: 20px"></div>
			</div>
			<div class="modal-body">
				<table class="table" id="table1">
				</table>
			</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal -->
</div>

login/templates/login/register.html
{% extends 'login/base.html' %}

{% load static %}
{% block title %}注册{% endblock %}
{% block static %}
<script src="{% static 'js/login/main.js' %}"></script>
<link href="{% static 'css/login/login.css' %}" rel="stylesheet"/>
{% endblock %}


{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
          {% include './components/teacher_verify.html' %}
          <form class='form-login' action="/register/" method="post" AUTOCOMPLETE="OFF">
              {% if messages %}
                <ul class="messages">
                   {% for message in messages %}
                      <script>alert('{{ message }}')</script>
                   {% endfor %}
                </ul>
              {% endif %}
              {% csrf_token %}
              <h2 class="text-center">欢迎注册</h2>
              <div class="form-group">
                <label for="id_username">用户名：</label>
                <input type="text" name='username' class="form-control" id="id_username" placeholder="Username" autofocus required>
              </div>
              <div class="form-group">
                <label for="id_display_name">昵称：</label>
                <input type="text" name='display_name' class="form-control" id="id_display_name" placeholder="Display name" autofocus required>
              </div>
              <div class="form-group">
                <label for="id_password">密码：</label>
                <input type="password" name='password1' class="form-control" id="id_password" placeholder="Password" required>
              </div>
              <div class="form-group">
                <label for="id_password2">再次输入密码：</label>
                <input type="password" name='password2' class="form-control" id="id_password2" placeholder="Password" required>
              </div>
              <button type="reset" class="btn btn-default pull-left">重置</button>
              <button type="submit" class="btn btn-primary pull-right">提交</button>
              <a class="teacher-verify pull-right" id="teacher_verify_trigger" data-toggle="modal" data-target="#teacher_verify_modal">我是教师</a>
          </form>


        </div>
    </div> <!-- /container -->

{% endblock %}

person_info/templates/person_info/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}个人信息{% endblock %}
{% block css %}<link href="{% static 'css/login.css' %}" rel="stylesheet"/>{% endblock %}

{% block content%}

<div>
    You are on your person information page.
    <br><br>
    <label for="id_username">你的用户名：</label>
    <p id="id_username">{{ username }}</p>
    <label for="id_password">你的密码：</label>
    <p id="id_password">{{ password }}</p>
    <label for="id_create_time">你的创建时间：</label>
    <p id="id_create_time">{{ create_time }}</p>
</div>
{% endblock%}